---
name: release to PyPI

on:
  push:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies & build wheel
        run: |
          pipx install poetry
          poetry install
          poetry build

      - name: Check the wheel
        run: |
          pipx install twine
          twine check dist/opensuse_distro_aliases-*whl

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags')
